### ISSUE TITLE
mobile UI improvements

### ISSUE THREAD

**Issue by pascalwhoop** [opitzconsulting/blog#6]
kann ich auch machen

**Comment by rattermeyer** [comment]
gerne, da du nicht schreibst was ...

**Comment by pascalwhoop** [comment]
<img width="1392" alt="screen shot 2015-09-28 at 16 29 49" src="https://cloud.githubusercontent.com/assets/2284951/10138298/2832c8b4-65fe-11e5-8ff1-0f7bc93587e4.png">

**Comment by pascalwhoop** [comment]
war kein UI Bug aufm Handy (hatte kurz auf die Page guguckt mitm Smartphone) sondern scheint ein Filepath Resolvement Issue zu sein

**Comment by codescape** [comment]
@pascalwhoop In der _config.yml steht ja auch die falsche URL drinnen.

**Comment by pascalwhoop** [comment]
0de53413941e1671051bd5faac0fc7256e998630
